---
- name: Including Global Variables
  include_vars: "{{ playbook_dir }}/config.yaml"

- name: Echo directory and File
  debug: Config Folder - {{ config_directory }} | Config File - {{ config_file }}
  
- name: Reading the file.xml file
  ansible.builtin.shell:
    cmd: cat "{{ config_file }}"
    chdir: "{{ config_directory }}"
  register: file_content

- name: "Print the file content to a console"
  debug:
    msg: "{{ file_content.stdout.replace('\t','  ').split('\n') }}"