---
- name: Restart the Clickhouse Service
  ansible.builtin.shell:
    cmd: systemctl restart clickhouse-server

- name: Status of the Clickhouse Service
  ansible.builtin.shell:
    cmd: systemctl status clickhouse-server
  register: status

- name: Status
  debug:
    msg: "{{ status.stdout.split('\n') }}"