---
- name: Including Global Variables
  include_vars: "{{ playbook_dir }}/config.yaml"

- name: Echo directory and File
  debug: Config Folder - {{ config_directory }} | Config File - {{ config_file }}

- name: Editing heartbeat_interval_ms to 12345
  community.general.xml:
    path: "{{ config_file }}"
    xpath: "{{ config_xpath }}"
    value: '12345'