---
- name: Including Global Variables
  include_vars: "{{ playbook_dir }}/config.yaml"

- name: Echo directory and File
  debug: Config Folder - {{ config_directory }} | Config File - {{ config_file }}

- name: Adding elements to another element
  community.general.xml:
    file: "{{ config_file }}"
    xpath: "{{ config_xpath }}"
    input_type: xml
    pretty_print: yes
    add_children:
      - "\n<chronicle_policy_disk2>\n\t<volumes>\n\t\t<chronicle_disk_volume2>\n\t\t\t<disk>data1</disk>\n\t\t</chronicle_disk_volume2>\n\t</volumes>\n</chronicle_policy_disk2>"