---
- name: Adding elements to another element
  community.general.xml:
    file: /root/tmp/file.xml
    xpath: /yandex/kafka
    input_type: xml
    pretty_print: yes
    add_children:
      - "<subtag2><auto_offset_reset>latest</auto_offset_reset><heartbeat_interval_ms>10000</heartbeat_interval_ms><session_timeout_ms>60000</session_timeout_ms><max_poll_interval_ms>300000</max_poll_interval_ms></subtag2>"