
---
- name: Check whether XML files present
  ansible.builtin.find:
    paths: /root/tmp
    patterns: '*.xml'

- name: Finding the files
  ansible.builtin.shell:
    cmd: ls | grep .xml
    chdir: /root/tmp
  register: xml_files

- name: Listing all the files
  debug:
    msg: "{{ xml_files.stdout.split('\n') }}"